exp:
  root_ckpt_dir: "./checkpoint_dir"
  root_log_dir: "./log"
  name: "scalemogen_snapmogen_bsq24_best_fid"
  device: "cuda:0"
  is_continue: false
  is_train: false
  seed: 10306

vq_name: "scalemogen_snapmogen_bsq24_indiv_joint"
vq_ckpt: "net_best_fid.tar"

data:
  name: "snapmogen"
  root_dir: "./data/SnapMoGen"
  unit_length: 8
  joint_num: 24
  dim_pose: 296
  fps: 30
  max_motion_length: 320
  motion_length: 120
  max_text_length: 120
  min_motion_length: 128

eval:
  eval_name: "vq_eval"
  batch_size: 100
  num_workers: 0
  shuffle: false
  deterministic_data: true
