exp:
  root_ckpt_dir: "./checkpoint_dir"
  root_log_dir: "./log"
  name: "scalemogen_humanml3d_bsq24"
  device: "cuda:0"
  is_continue: false
  is_train: false
  seed: 10306

vq_name: "scalemogen_humanml3d_bsq24"
vq_ckpt: "latest.tar"

data:
  name: "humanml3d"
  root_dir: "./data/HumanML3D"
  unit_length: 4
  joint_num: 22
  dim_pose: 263
  fps: 20
  max_motion_length: 196
  motion_length: 128
  max_text_length: 20
  min_motion_length: 40
  contact_joints: [7, 10, 8, 11]

eval:
  eval_name: "scalemogen_eval_hml"
  batch_size: 32
  num_workers: 0
  shuffle: false
  deterministic_data: true
  model_ckpt: "best_fid_ep_228_it_248.pth"
  repeat_times: 20
  cal_mm: true
  cfg: 7.0
  tau: 1.3
  sampling_per_bits: 1
  sampling_device: "cuda"
  sampling_method: "multinomial"
  cfg_insertion_layer: 0
  enable_positive_prompt: 0
  text_encoder_dtype: "fp32"
  text_encoder_device: "cuda:0"
  use_bf16: false
  seed_mode: "deterministic"
  base_seed: 10306
