exp:
  root_ckpt_dir: "./checkpoint_dir"
  root_log_dir: "./log"
  name: "scalemogen_snapmogen_bsq24_best_fid"
  device: "cuda:0"
  is_continue: false
  is_train: false
  seed: 10306

vq_name: "scalemogen_snapmogen_bsq24_indiv_joint"
vq_ckpt: "net_best_fid.tar"

data:
  name: "snapmogen"
  root_dir: "./data/SnapMoGen"
  unit_length: 8
  joint_num: 24
  dim_pose: 296
  fps: 30
  max_motion_length: 320
  motion_length: 120
  max_text_length: 120
  min_motion_length: 128

eval:
  eval_name: "scalemogen_eval"
  batch_size: 100
  num_workers: 0
  shuffle: false
  deterministic_data: true
  model_ckpt: "ckpt-best.pth"
  repeat_times: 20
  cal_mm: true
  cfg: 7.0
  tau: 1.3
  sampling_per_bits: 1
  sampling_device: "cuda"
  sampling_method: "multinomial"
  cfg_insertion_layer: 0
  enable_positive_prompt: 0
  text_encoder_dtype: "fp32"
  text_encoder_device: "cuda:0"
  use_bf16: false
  seed_mode: "deterministic"
  base_seed: 10306
