exp:
  root_ckpt_dir: "./checkpoint_dir"
  root_log_dir: "./log"
  name: "scalemogen_snapmogen_bsq24_indiv_joint"
  device: "cuda:0"
  is_continue: false
  is_train: true
  seed: 10306

vq_name: "scalemogen_snapmogen_bsq24_indiv_joint"
vq_ckpt: "latest.tar"

data:
  name: "snapmogen"
  root_dir: "./data/SnapMoGen"
  unit_length: 8
  joint_num: 24
  dim_pose: 296
  fps: 30
  max_motion_length: 320
  motion_length: 120
  max_text_length: 120
  min_motion_length: 128
  contact_joints: [18, 19, 22, 23]

quantizer:
  bsq_dim: 24
  temp_scales: [80, 40, 20, 10, 5, 2, 1]
  ctf_mapping_id: 3

training:
  batch_size: 32
  max_epoch: 500
  log_every: 100
